/********************************************************************************
** Form generated from reading UI file 'hlsl1.ui'
**
** Created by: Qt User Interface Compiler version 5.11.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HLSL1_H
#define UI_HLSL1_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_hlsl1Class
{
public:
    QWidget *centralWidget;
    QLabel *ResultDisplayLabel;
    QLabel *label_3;
    QPushButton *ImportButton;
    QLabel *label_2;
    QPushButton *KeyingMatteButton;
    QSlider *ScreenBalanceSlider;
    QLabel *label;
    QLabel *ScreenBalanceLabel;
    QLabel *ScreenBalanceValueLabel;
    QLabel *ImageDisplayLabel;
    QPushButton *SelectImageButton;
    QPushButton *KeyingImageButton;
    QLabel *ResultDisplayLabel_2;
    QLabel *despillFactorLabel;
    QLabel *despillBalanceLabel;
    QLabel *despillFactorValueLabel;
    QLabel *despillBalanceValueLabel;
    QSlider *despillFactorSlider;
    QSlider *despillBalanceSlider;
    QLabel *edgeKernelRadiusLabel;
    QSlider *edgeKernelToleranceSlider;
    QLabel *PreBlurValueLabel;
    QLabel *clipBlackLabel;
    QSlider *clipBlackSlider;
    QLabel *edgeKernelToleranceValueLabel;
    QSlider *PreBlurSlider;
    QLabel *edgeKernelRadiusValueLabel;
    QLabel *PreBlurLabel;
    QSlider *clipWhiteSlider;
    QLabel *clipBlackValueLabel;
    QSlider *edgeKernelRadiusSlider;
    QLabel *clipWhiteValueLabel;
    QLabel *edgeKernelToleranceLabel;
    QLabel *clipWhiteLabel;
    QLabel *PostBlurValueLabel;
    QSlider *PostBlurSlider;
    QLabel *PostBlurLabel;
    QLabel *featherFalloffValueLabel;
    QSlider *DilateErodeSlider;
    QLabel *featherDistanceValueLabel;
    QLabel *featherDistanceLabel;
    QSlider *featherDistanceSlider;
    QLabel *DilateErodeLabel;
    QLabel *featherFalloffLabel;
    QLabel *DilateErodeValueLabel;
    QComboBox *featherFalloffComboBox;
    QComboBox *MaskComboBox;
    QLabel *XLabel_2;
    QLabel *TransparentLabel_2;
    QComboBox *MaskTypeComboBox;
    QDoubleSpinBox *HeightDoubleSpinBox;
    QDoubleSpinBox *XDoubleSpinBox_2;
    QComboBox *MaskComboBox_2;
    QDoubleSpinBox *RotationDoubleSpinBox;
    QCheckBox *CoreMatteCheckBox;
    QLabel *XLabel;
    QLabel *RotationLabel_2;
    QLabel *WidthLabel;
    QDoubleSpinBox *TransparentDoubleSpinBox_2;
    QDoubleSpinBox *WidthDoubleSpinBox_2;
    QDoubleSpinBox *HeightDoubleSpinBox_2;
    QComboBox *MaskTypeComboBox_2;
    QLabel *MaskLabel_2;
    QLabel *WidthLabel_2;
    QLabel *MaskTypeLabel;
    QDoubleSpinBox *TransparentDoubleSpinBox;
    QDoubleSpinBox *YDoubleSpinBox;
    QLabel *TransparentLabel;
    QLabel *HeightLabel_2;
    QLabel *HeightLabel;
    QLabel *MaskLabel;
    QDoubleSpinBox *XDoubleSpinBox;
    QLabel *YLabel;
    QLabel *MaskTypeLabel_2;
    QLabel *YLabel_2;
    QDoubleSpinBox *RotationDoubleSpinBox_2;
    QDoubleSpinBox *YDoubleSpinBox_2;
    QLabel *RotationLabel;
    QCheckBox *GarbageMatteCheckBox;
    QDoubleSpinBox *WidthDoubleSpinBox;
    QRadioButton *CompositeRadioButton;
    QPushButton *SelectBackgroundButton;
    QPushButton *SelectVideoButton;
    QPushButton *SelectKinectButton;
    QPushButton *getOneFrameButton;
    QLabel *gammaLabel;
    QLabel *contrastLabel;
    QLabel *sharpLabel;
    QLabel *brightnessLabel;
    QLabel *contrastValueLabel;
    QSlider *sharpSlider;
    QSlider *contrastSlider;
    QSlider *gammaSlider;
    QLabel *sharpValueLabel;
    QSlider *brightnessSlider;
    QLabel *gammaValueLabel;
    QLabel *brightnessValueLabel;
    QLabel *binarizationLabel;
    QCheckBox *binaryCheckBox;
    QLabel *binarizationValueLabel;
    QSlider *binarizationSlider;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *hlsl1Class)
    {
        if (hlsl1Class->objectName().isEmpty())
            hlsl1Class->setObjectName(QStringLiteral("hlsl1Class"));
        hlsl1Class->resize(1116, 863);
        centralWidget = new QWidget(hlsl1Class);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        ResultDisplayLabel = new QLabel(centralWidget);
        ResultDisplayLabel->setObjectName(QStringLiteral("ResultDisplayLabel"));
        ResultDisplayLabel->setGeometry(QRect(10, 500, 411, 291));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(640, 630, 71, 21));
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(14);
        label_3->setFont(font);
        ImportButton = new QPushButton(centralWidget);
        ImportButton->setObjectName(QStringLiteral("ImportButton"));
        ImportButton->setGeometry(QRect(970, 10, 120, 30));
        QFont font1;
        font1.setFamily(QStringLiteral("Arial"));
        font1.setPointSize(12);
        ImportButton->setFont(font1);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 420, 71, 21));
        label_2->setFont(font);
        KeyingMatteButton = new QPushButton(centralWidget);
        KeyingMatteButton->setObjectName(QStringLiteral("KeyingMatteButton"));
        KeyingMatteButton->setGeometry(QRect(710, 10, 120, 30));
        KeyingMatteButton->setFont(font1);
        ScreenBalanceSlider = new QSlider(centralWidget);
        ScreenBalanceSlider->setObjectName(QStringLiteral("ScreenBalanceSlider"));
        ScreenBalanceSlider->setGeometry(QRect(685, 50, 160, 22));
        ScreenBalanceSlider->setOrientation(Qt::Horizontal);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 71, 21));
        label->setFont(font);
        ScreenBalanceLabel = new QLabel(centralWidget);
        ScreenBalanceLabel->setObjectName(QStringLiteral("ScreenBalanceLabel"));
        ScreenBalanceLabel->setGeometry(QRect(590, 50, 110, 30));
        QFont font2;
        font2.setFamily(QStringLiteral("Arial"));
        font2.setPointSize(10);
        ScreenBalanceLabel->setFont(font2);
        ScreenBalanceValueLabel = new QLabel(centralWidget);
        ScreenBalanceValueLabel->setObjectName(QStringLiteral("ScreenBalanceValueLabel"));
        ScreenBalanceValueLabel->setGeometry(QRect(865, 50, 72, 15));
        ImageDisplayLabel = new QLabel(centralWidget);
        ImageDisplayLabel->setObjectName(QStringLiteral("ImageDisplayLabel"));
        ImageDisplayLabel->setGeometry(QRect(10, 50, 411, 291));
        SelectImageButton = new QPushButton(centralWidget);
        SelectImageButton->setObjectName(QStringLiteral("SelectImageButton"));
        SelectImageButton->setGeometry(QRect(580, 10, 120, 30));
        SelectImageButton->setFont(font1);
        KeyingImageButton = new QPushButton(centralWidget);
        KeyingImageButton->setObjectName(QStringLiteral("KeyingImageButton"));
        KeyingImageButton->setGeometry(QRect(840, 10, 120, 30));
        KeyingImageButton->setFont(font1);
        ResultDisplayLabel_2 = new QLabel(centralWidget);
        ResultDisplayLabel_2->setObjectName(QStringLiteral("ResultDisplayLabel_2"));
        ResultDisplayLabel_2->setGeometry(QRect(580, 500, 411, 291));
        despillFactorLabel = new QLabel(centralWidget);
        despillFactorLabel->setObjectName(QStringLiteral("despillFactorLabel"));
        despillFactorLabel->setGeometry(QRect(590, 80, 110, 30));
        QFont font3;
        font3.setFamily(QStringLiteral("Arial"));
        font3.setPointSize(9);
        despillFactorLabel->setFont(font3);
        despillBalanceLabel = new QLabel(centralWidget);
        despillBalanceLabel->setObjectName(QStringLiteral("despillBalanceLabel"));
        despillBalanceLabel->setGeometry(QRect(590, 110, 110, 30));
        despillBalanceLabel->setFont(font3);
        despillFactorValueLabel = new QLabel(centralWidget);
        despillFactorValueLabel->setObjectName(QStringLiteral("despillFactorValueLabel"));
        despillFactorValueLabel->setGeometry(QRect(865, 80, 72, 15));
        despillBalanceValueLabel = new QLabel(centralWidget);
        despillBalanceValueLabel->setObjectName(QStringLiteral("despillBalanceValueLabel"));
        despillBalanceValueLabel->setGeometry(QRect(865, 110, 72, 15));
        despillFactorSlider = new QSlider(centralWidget);
        despillFactorSlider->setObjectName(QStringLiteral("despillFactorSlider"));
        despillFactorSlider->setGeometry(QRect(685, 80, 160, 22));
        despillFactorSlider->setOrientation(Qt::Horizontal);
        despillBalanceSlider = new QSlider(centralWidget);
        despillBalanceSlider->setObjectName(QStringLiteral("despillBalanceSlider"));
        despillBalanceSlider->setGeometry(QRect(685, 110, 160, 22));
        despillBalanceSlider->setOrientation(Qt::Horizontal);
        edgeKernelRadiusLabel = new QLabel(centralWidget);
        edgeKernelRadiusLabel->setObjectName(QStringLiteral("edgeKernelRadiusLabel"));
        edgeKernelRadiusLabel->setGeometry(QRect(590, 170, 110, 30));
        edgeKernelRadiusLabel->setFont(font3);
        edgeKernelToleranceSlider = new QSlider(centralWidget);
        edgeKernelToleranceSlider->setObjectName(QStringLiteral("edgeKernelToleranceSlider"));
        edgeKernelToleranceSlider->setGeometry(QRect(685, 200, 160, 22));
        edgeKernelToleranceSlider->setOrientation(Qt::Horizontal);
        PreBlurValueLabel = new QLabel(centralWidget);
        PreBlurValueLabel->setObjectName(QStringLiteral("PreBlurValueLabel"));
        PreBlurValueLabel->setGeometry(QRect(865, 140, 72, 15));
        clipBlackLabel = new QLabel(centralWidget);
        clipBlackLabel->setObjectName(QStringLiteral("clipBlackLabel"));
        clipBlackLabel->setGeometry(QRect(590, 230, 110, 30));
        clipBlackLabel->setFont(font3);
        clipBlackSlider = new QSlider(centralWidget);
        clipBlackSlider->setObjectName(QStringLiteral("clipBlackSlider"));
        clipBlackSlider->setGeometry(QRect(685, 230, 160, 22));
        clipBlackSlider->setOrientation(Qt::Horizontal);
        edgeKernelToleranceValueLabel = new QLabel(centralWidget);
        edgeKernelToleranceValueLabel->setObjectName(QStringLiteral("edgeKernelToleranceValueLabel"));
        edgeKernelToleranceValueLabel->setGeometry(QRect(865, 200, 72, 15));
        PreBlurSlider = new QSlider(centralWidget);
        PreBlurSlider->setObjectName(QStringLiteral("PreBlurSlider"));
        PreBlurSlider->setGeometry(QRect(685, 140, 160, 22));
        PreBlurSlider->setOrientation(Qt::Horizontal);
        edgeKernelRadiusValueLabel = new QLabel(centralWidget);
        edgeKernelRadiusValueLabel->setObjectName(QStringLiteral("edgeKernelRadiusValueLabel"));
        edgeKernelRadiusValueLabel->setGeometry(QRect(865, 170, 72, 15));
        PreBlurLabel = new QLabel(centralWidget);
        PreBlurLabel->setObjectName(QStringLiteral("PreBlurLabel"));
        PreBlurLabel->setGeometry(QRect(590, 140, 110, 30));
        PreBlurLabel->setFont(font2);
        clipWhiteSlider = new QSlider(centralWidget);
        clipWhiteSlider->setObjectName(QStringLiteral("clipWhiteSlider"));
        clipWhiteSlider->setGeometry(QRect(685, 260, 160, 22));
        clipWhiteSlider->setOrientation(Qt::Horizontal);
        clipBlackValueLabel = new QLabel(centralWidget);
        clipBlackValueLabel->setObjectName(QStringLiteral("clipBlackValueLabel"));
        clipBlackValueLabel->setGeometry(QRect(865, 230, 72, 15));
        edgeKernelRadiusSlider = new QSlider(centralWidget);
        edgeKernelRadiusSlider->setObjectName(QStringLiteral("edgeKernelRadiusSlider"));
        edgeKernelRadiusSlider->setGeometry(QRect(685, 170, 160, 22));
        edgeKernelRadiusSlider->setOrientation(Qt::Horizontal);
        clipWhiteValueLabel = new QLabel(centralWidget);
        clipWhiteValueLabel->setObjectName(QStringLiteral("clipWhiteValueLabel"));
        clipWhiteValueLabel->setGeometry(QRect(865, 260, 72, 15));
        edgeKernelToleranceLabel = new QLabel(centralWidget);
        edgeKernelToleranceLabel->setObjectName(QStringLiteral("edgeKernelToleranceLabel"));
        edgeKernelToleranceLabel->setGeometry(QRect(590, 200, 110, 30));
        edgeKernelToleranceLabel->setFont(font3);
        clipWhiteLabel = new QLabel(centralWidget);
        clipWhiteLabel->setObjectName(QStringLiteral("clipWhiteLabel"));
        clipWhiteLabel->setGeometry(QRect(590, 260, 110, 30));
        clipWhiteLabel->setFont(font3);
        PostBlurValueLabel = new QLabel(centralWidget);
        PostBlurValueLabel->setObjectName(QStringLiteral("PostBlurValueLabel"));
        PostBlurValueLabel->setGeometry(QRect(870, 290, 72, 15));
        PostBlurSlider = new QSlider(centralWidget);
        PostBlurSlider->setObjectName(QStringLiteral("PostBlurSlider"));
        PostBlurSlider->setGeometry(QRect(685, 290, 160, 22));
        PostBlurSlider->setOrientation(Qt::Horizontal);
        PostBlurLabel = new QLabel(centralWidget);
        PostBlurLabel->setObjectName(QStringLiteral("PostBlurLabel"));
        PostBlurLabel->setGeometry(QRect(590, 290, 110, 30));
        PostBlurLabel->setFont(font3);
        featherFalloffValueLabel = new QLabel(centralWidget);
        featherFalloffValueLabel->setObjectName(QStringLiteral("featherFalloffValueLabel"));
        featherFalloffValueLabel->setGeometry(QRect(870, 350, 72, 15));
        DilateErodeSlider = new QSlider(centralWidget);
        DilateErodeSlider->setObjectName(QStringLiteral("DilateErodeSlider"));
        DilateErodeSlider->setGeometry(QRect(685, 320, 160, 22));
        DilateErodeSlider->setOrientation(Qt::Horizontal);
        featherDistanceValueLabel = new QLabel(centralWidget);
        featherDistanceValueLabel->setObjectName(QStringLiteral("featherDistanceValueLabel"));
        featherDistanceValueLabel->setGeometry(QRect(870, 380, 72, 15));
        featherDistanceLabel = new QLabel(centralWidget);
        featherDistanceLabel->setObjectName(QStringLiteral("featherDistanceLabel"));
        featherDistanceLabel->setGeometry(QRect(590, 380, 110, 30));
        featherDistanceLabel->setFont(font3);
        featherDistanceSlider = new QSlider(centralWidget);
        featherDistanceSlider->setObjectName(QStringLiteral("featherDistanceSlider"));
        featherDistanceSlider->setGeometry(QRect(685, 380, 160, 22));
        featherDistanceSlider->setOrientation(Qt::Horizontal);
        DilateErodeLabel = new QLabel(centralWidget);
        DilateErodeLabel->setObjectName(QStringLiteral("DilateErodeLabel"));
        DilateErodeLabel->setGeometry(QRect(590, 320, 110, 30));
        DilateErodeLabel->setFont(font3);
        featherFalloffLabel = new QLabel(centralWidget);
        featherFalloffLabel->setObjectName(QStringLiteral("featherFalloffLabel"));
        featherFalloffLabel->setGeometry(QRect(590, 350, 110, 30));
        QFont font4;
        font4.setFamily(QStringLiteral("Arial"));
        featherFalloffLabel->setFont(font4);
        DilateErodeValueLabel = new QLabel(centralWidget);
        DilateErodeValueLabel->setObjectName(QStringLiteral("DilateErodeValueLabel"));
        DilateErodeValueLabel->setGeometry(QRect(870, 320, 72, 15));
        featherFalloffComboBox = new QComboBox(centralWidget);
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->addItem(QString());
        featherFalloffComboBox->setObjectName(QStringLiteral("featherFalloffComboBox"));
        featherFalloffComboBox->setGeometry(QRect(685, 350, 160, 22));
        MaskComboBox = new QComboBox(centralWidget);
        MaskComboBox->addItem(QString());
        MaskComboBox->addItem(QString());
        MaskComboBox->setObjectName(QStringLiteral("MaskComboBox"));
        MaskComboBox->setGeometry(QRect(1010, 76, 70, 22));
        XLabel_2 = new QLabel(centralWidget);
        XLabel_2->setObjectName(QStringLiteral("XLabel_2"));
        XLabel_2->setGeometry(QRect(950, 396, 72, 20));
        TransparentLabel_2 = new QLabel(centralWidget);
        TransparentLabel_2->setObjectName(QStringLiteral("TransparentLabel_2"));
        TransparentLabel_2->setGeometry(QRect(950, 546, 72, 20));
        MaskTypeComboBox = new QComboBox(centralWidget);
        MaskTypeComboBox->addItem(QString());
        MaskTypeComboBox->addItem(QString());
        MaskTypeComboBox->addItem(QString());
        MaskTypeComboBox->addItem(QString());
        MaskTypeComboBox->setObjectName(QStringLiteral("MaskTypeComboBox"));
        MaskTypeComboBox->setGeometry(QRect(1020, 296, 61, 22));
        HeightDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        HeightDoubleSpinBox->setObjectName(QStringLiteral("HeightDoubleSpinBox"));
        HeightDoubleSpinBox->setGeometry(QRect(1010, 200, 70, 20));
        XDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        XDoubleSpinBox_2->setObjectName(QStringLiteral("XDoubleSpinBox_2"));
        XDoubleSpinBox_2->setGeometry(QRect(1010, 396, 70, 20));
        MaskComboBox_2 = new QComboBox(centralWidget);
        MaskComboBox_2->addItem(QString());
        MaskComboBox_2->addItem(QString());
        MaskComboBox_2->setObjectName(QStringLiteral("MaskComboBox_2"));
        MaskComboBox_2->setGeometry(QRect(1010, 362, 70, 22));
        RotationDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        RotationDoubleSpinBox->setObjectName(QStringLiteral("RotationDoubleSpinBox"));
        RotationDoubleSpinBox->setGeometry(QRect(1010, 230, 70, 20));
        CoreMatteCheckBox = new QCheckBox(centralWidget);
        CoreMatteCheckBox->setObjectName(QStringLiteral("CoreMatteCheckBox"));
        CoreMatteCheckBox->setGeometry(QRect(950, 336, 91, 19));
        XLabel = new QLabel(centralWidget);
        XLabel->setObjectName(QStringLiteral("XLabel"));
        XLabel->setGeometry(QRect(950, 110, 72, 20));
        RotationLabel_2 = new QLabel(centralWidget);
        RotationLabel_2->setObjectName(QStringLiteral("RotationLabel_2"));
        RotationLabel_2->setGeometry(QRect(950, 516, 72, 20));
        WidthLabel = new QLabel(centralWidget);
        WidthLabel->setObjectName(QStringLiteral("WidthLabel"));
        WidthLabel->setGeometry(QRect(950, 170, 72, 20));
        TransparentDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        TransparentDoubleSpinBox_2->setObjectName(QStringLiteral("TransparentDoubleSpinBox_2"));
        TransparentDoubleSpinBox_2->setGeometry(QRect(1010, 546, 70, 20));
        WidthDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        WidthDoubleSpinBox_2->setObjectName(QStringLiteral("WidthDoubleSpinBox_2"));
        WidthDoubleSpinBox_2->setGeometry(QRect(1010, 456, 70, 20));
        HeightDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        HeightDoubleSpinBox_2->setObjectName(QStringLiteral("HeightDoubleSpinBox_2"));
        HeightDoubleSpinBox_2->setGeometry(QRect(1010, 486, 70, 20));
        MaskTypeComboBox_2 = new QComboBox(centralWidget);
        MaskTypeComboBox_2->addItem(QString());
        MaskTypeComboBox_2->addItem(QString());
        MaskTypeComboBox_2->addItem(QString());
        MaskTypeComboBox_2->addItem(QString());
        MaskTypeComboBox_2->setObjectName(QStringLiteral("MaskTypeComboBox_2"));
        MaskTypeComboBox_2->setGeometry(QRect(1020, 582, 61, 22));
        MaskLabel_2 = new QLabel(centralWidget);
        MaskLabel_2->setObjectName(QStringLiteral("MaskLabel_2"));
        MaskLabel_2->setGeometry(QRect(950, 366, 72, 15));
        WidthLabel_2 = new QLabel(centralWidget);
        WidthLabel_2->setObjectName(QStringLiteral("WidthLabel_2"));
        WidthLabel_2->setGeometry(QRect(950, 456, 72, 20));
        MaskTypeLabel = new QLabel(centralWidget);
        MaskTypeLabel->setObjectName(QStringLiteral("MaskTypeLabel"));
        MaskTypeLabel->setGeometry(QRect(950, 300, 72, 15));
        TransparentDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        TransparentDoubleSpinBox->setObjectName(QStringLiteral("TransparentDoubleSpinBox"));
        TransparentDoubleSpinBox->setGeometry(QRect(1010, 260, 70, 20));
        YDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        YDoubleSpinBox->setObjectName(QStringLiteral("YDoubleSpinBox"));
        YDoubleSpinBox->setGeometry(QRect(1010, 140, 70, 20));
        TransparentLabel = new QLabel(centralWidget);
        TransparentLabel->setObjectName(QStringLiteral("TransparentLabel"));
        TransparentLabel->setGeometry(QRect(950, 260, 72, 20));
        HeightLabel_2 = new QLabel(centralWidget);
        HeightLabel_2->setObjectName(QStringLiteral("HeightLabel_2"));
        HeightLabel_2->setGeometry(QRect(950, 486, 72, 20));
        HeightLabel = new QLabel(centralWidget);
        HeightLabel->setObjectName(QStringLiteral("HeightLabel"));
        HeightLabel->setGeometry(QRect(950, 200, 72, 20));
        MaskLabel = new QLabel(centralWidget);
        MaskLabel->setObjectName(QStringLiteral("MaskLabel"));
        MaskLabel->setGeometry(QRect(950, 80, 72, 15));
        XDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        XDoubleSpinBox->setObjectName(QStringLiteral("XDoubleSpinBox"));
        XDoubleSpinBox->setGeometry(QRect(1010, 110, 70, 20));
        YLabel = new QLabel(centralWidget);
        YLabel->setObjectName(QStringLiteral("YLabel"));
        YLabel->setGeometry(QRect(950, 140, 72, 20));
        MaskTypeLabel_2 = new QLabel(centralWidget);
        MaskTypeLabel_2->setObjectName(QStringLiteral("MaskTypeLabel_2"));
        MaskTypeLabel_2->setGeometry(QRect(950, 586, 72, 15));
        YLabel_2 = new QLabel(centralWidget);
        YLabel_2->setObjectName(QStringLiteral("YLabel_2"));
        YLabel_2->setGeometry(QRect(950, 426, 72, 20));
        RotationDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        RotationDoubleSpinBox_2->setObjectName(QStringLiteral("RotationDoubleSpinBox_2"));
        RotationDoubleSpinBox_2->setGeometry(QRect(1010, 516, 70, 20));
        YDoubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        YDoubleSpinBox_2->setObjectName(QStringLiteral("YDoubleSpinBox_2"));
        YDoubleSpinBox_2->setGeometry(QRect(1010, 426, 70, 20));
        RotationLabel = new QLabel(centralWidget);
        RotationLabel->setObjectName(QStringLiteral("RotationLabel"));
        RotationLabel->setGeometry(QRect(950, 230, 72, 20));
        GarbageMatteCheckBox = new QCheckBox(centralWidget);
        GarbageMatteCheckBox->setObjectName(QStringLiteral("GarbageMatteCheckBox"));
        GarbageMatteCheckBox->setGeometry(QRect(950, 50, 91, 19));
        WidthDoubleSpinBox = new QDoubleSpinBox(centralWidget);
        WidthDoubleSpinBox->setObjectName(QStringLiteral("WidthDoubleSpinBox"));
        WidthDoubleSpinBox->setGeometry(QRect(1010, 170, 70, 20));
        CompositeRadioButton = new QRadioButton(centralWidget);
        CompositeRadioButton->setObjectName(QStringLiteral("CompositeRadioButton"));
        CompositeRadioButton->setGeometry(QRect(440, 50, 120, 30));
        SelectBackgroundButton = new QPushButton(centralWidget);
        SelectBackgroundButton->setObjectName(QStringLiteral("SelectBackgroundButton"));
        SelectBackgroundButton->setGeometry(QRect(440, 10, 131, 30));
        SelectBackgroundButton->setFont(font1);
        SelectVideoButton = new QPushButton(centralWidget);
        SelectVideoButton->setObjectName(QStringLiteral("SelectVideoButton"));
        SelectVideoButton->setGeometry(QRect(440, 80, 120, 30));
        SelectVideoButton->setFont(font1);
        SelectKinectButton = new QPushButton(centralWidget);
        SelectKinectButton->setObjectName(QStringLiteral("SelectKinectButton"));
        SelectKinectButton->setGeometry(QRect(440, 250, 120, 30));
        SelectKinectButton->setFont(font1);
        getOneFrameButton = new QPushButton(centralWidget);
        getOneFrameButton->setObjectName(QStringLiteral("getOneFrameButton"));
        getOneFrameButton->setGeometry(QRect(440, 130, 121, 51));
        getOneFrameButton->setFont(font1);
        getOneFrameButton->setCheckable(false);
        getOneFrameButton->setAutoRepeat(false);
        getOneFrameButton->setAutoExclusive(false);
        gammaLabel = new QLabel(centralWidget);
        gammaLabel->setObjectName(QStringLiteral("gammaLabel"));
        gammaLabel->setGeometry(QRect(580, 410, 110, 30));
        gammaLabel->setFont(font3);
        contrastLabel = new QLabel(centralWidget);
        contrastLabel->setObjectName(QStringLiteral("contrastLabel"));
        contrastLabel->setGeometry(QRect(580, 470, 110, 30));
        contrastLabel->setFont(font3);
        sharpLabel = new QLabel(centralWidget);
        sharpLabel->setObjectName(QStringLiteral("sharpLabel"));
        sharpLabel->setGeometry(QRect(580, 500, 110, 30));
        sharpLabel->setFont(font3);
        brightnessLabel = new QLabel(centralWidget);
        brightnessLabel->setObjectName(QStringLiteral("brightnessLabel"));
        brightnessLabel->setGeometry(QRect(580, 440, 110, 30));
        brightnessLabel->setFont(font3);
        contrastValueLabel = new QLabel(centralWidget);
        contrastValueLabel->setObjectName(QStringLiteral("contrastValueLabel"));
        contrastValueLabel->setGeometry(QRect(870, 480, 72, 15));
        sharpSlider = new QSlider(centralWidget);
        sharpSlider->setObjectName(QStringLiteral("sharpSlider"));
        sharpSlider->setGeometry(QRect(685, 510, 160, 22));
        sharpSlider->setOrientation(Qt::Horizontal);
        contrastSlider = new QSlider(centralWidget);
        contrastSlider->setObjectName(QStringLiteral("contrastSlider"));
        contrastSlider->setGeometry(QRect(685, 480, 160, 22));
        contrastSlider->setOrientation(Qt::Horizontal);
        gammaSlider = new QSlider(centralWidget);
        gammaSlider->setObjectName(QStringLiteral("gammaSlider"));
        gammaSlider->setGeometry(QRect(685, 420, 160, 22));
        gammaSlider->setOrientation(Qt::Horizontal);
        sharpValueLabel = new QLabel(centralWidget);
        sharpValueLabel->setObjectName(QStringLiteral("sharpValueLabel"));
        sharpValueLabel->setGeometry(QRect(870, 510, 72, 15));
        brightnessSlider = new QSlider(centralWidget);
        brightnessSlider->setObjectName(QStringLiteral("brightnessSlider"));
        brightnessSlider->setGeometry(QRect(685, 450, 160, 22));
        brightnessSlider->setOrientation(Qt::Horizontal);
        gammaValueLabel = new QLabel(centralWidget);
        gammaValueLabel->setObjectName(QStringLiteral("gammaValueLabel"));
        gammaValueLabel->setGeometry(QRect(870, 420, 72, 15));
        brightnessValueLabel = new QLabel(centralWidget);
        brightnessValueLabel->setObjectName(QStringLiteral("brightnessValueLabel"));
        brightnessValueLabel->setGeometry(QRect(870, 450, 72, 15));
        binarizationLabel = new QLabel(centralWidget);
        binarizationLabel->setObjectName(QStringLiteral("binarizationLabel"));
        binarizationLabel->setGeometry(QRect(590, 530, 110, 30));
        binarizationLabel->setFont(font3);
        binaryCheckBox = new QCheckBox(centralWidget);
        binaryCheckBox->setObjectName(QStringLiteral("binaryCheckBox"));
        binaryCheckBox->setGeometry(QRect(590, 570, 91, 19));
        binarizationValueLabel = new QLabel(centralWidget);
        binarizationValueLabel->setObjectName(QStringLiteral("binarizationValueLabel"));
        binarizationValueLabel->setGeometry(QRect(870, 530, 72, 15));
        binarizationSlider = new QSlider(centralWidget);
        binarizationSlider->setObjectName(QStringLiteral("binarizationSlider"));
        binarizationSlider->setGeometry(QRect(685, 530, 160, 22));
        binarizationSlider->setOrientation(Qt::Horizontal);
        hlsl1Class->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(hlsl1Class);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1116, 18));
        hlsl1Class->setMenuBar(menuBar);
        mainToolBar = new QToolBar(hlsl1Class);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        hlsl1Class->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(hlsl1Class);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        hlsl1Class->setStatusBar(statusBar);

        retranslateUi(hlsl1Class);

        QMetaObject::connectSlotsByName(hlsl1Class);
    } // setupUi

    void retranslateUi(QMainWindow *hlsl1Class)
    {
        hlsl1Class->setWindowTitle(QApplication::translate("hlsl1Class", "hlsl1", nullptr));
        ResultDisplayLabel->setText(QString());
        label_3->setText(QApplication::translate("hlsl1Class", "\345\211\215\346\231\257\345\233\276", nullptr));
        ImportButton->setText(QApplication::translate("hlsl1Class", "\345\257\274\345\207\272\347\273\223\346\236\234", nullptr));
        label_2->setText(QApplication::translate("hlsl1Class", "\350\222\231\347\211\210", nullptr));
        KeyingMatteButton->setText(QApplication::translate("hlsl1Class", "\350\222\231\347\211\210", nullptr));
        label->setText(QApplication::translate("hlsl1Class", "\345\216\237\345\233\276", nullptr));
        ScreenBalanceLabel->setText(QApplication::translate("hlsl1Class", "\345\261\217\345\271\225\345\271\263\350\241\241", nullptr));
        ScreenBalanceValueLabel->setText(QApplication::translate("hlsl1Class", "0.500", nullptr));
        ImageDisplayLabel->setText(QString());
        SelectImageButton->setText(QApplication::translate("hlsl1Class", "\345\257\274\345\205\245\345\233\276\345\203\217", nullptr));
        KeyingImageButton->setText(QApplication::translate("hlsl1Class", "\345\211\215\346\231\257", nullptr));
        ResultDisplayLabel_2->setText(QString());
        despillFactorLabel->setText(QApplication::translate("hlsl1Class", "\351\235\236\346\272\242\345\207\272\347\263\273\346\225\260", nullptr));
        despillBalanceLabel->setText(QApplication::translate("hlsl1Class", "\351\235\236\346\272\242\345\207\272\345\271\263\350\241\241", nullptr));
        despillFactorValueLabel->setText(QApplication::translate("hlsl1Class", "1.000", nullptr));
        despillBalanceValueLabel->setText(QApplication::translate("hlsl1Class", "0.500", nullptr));
        edgeKernelRadiusLabel->setText(QApplication::translate("hlsl1Class", "\350\276\271\347\274\230\346\240\270\345\277\203\345\215\212\345\276\204", nullptr));
        PreBlurValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        clipBlackLabel->setText(QApplication::translate("hlsl1Class", "\351\222\263\345\210\266\351\273\221\350\211\262", nullptr));
        edgeKernelToleranceValueLabel->setText(QApplication::translate("hlsl1Class", "0.100", nullptr));
        edgeKernelRadiusValueLabel->setText(QApplication::translate("hlsl1Class", "3", nullptr));
        PreBlurLabel->setText(QApplication::translate("hlsl1Class", "\351\242\204\346\250\241\347\263\212", nullptr));
        clipBlackValueLabel->setText(QApplication::translate("hlsl1Class", "0.000", nullptr));
        clipWhiteValueLabel->setText(QApplication::translate("hlsl1Class", "1.000", nullptr));
        edgeKernelToleranceLabel->setText(QApplication::translate("hlsl1Class", "\350\276\271\347\274\230\346\240\270\345\277\203\345\256\271\345\267\256", nullptr));
        clipWhiteLabel->setText(QApplication::translate("hlsl1Class", "\351\222\263\345\210\266\347\231\275\350\211\262", nullptr));
        PostBlurValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        PostBlurLabel->setText(QApplication::translate("hlsl1Class", "\345\220\216\346\234\237\346\250\241\347\263\212", nullptr));
        featherFalloffValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        featherDistanceValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        featherDistanceLabel->setText(QApplication::translate("hlsl1Class", "\347\276\275\345\214\226\350\267\235\347\246\273", nullptr));
        DilateErodeLabel->setText(QApplication::translate("hlsl1Class", "\350\206\250\350\203\200/\350\205\220\350\232\200", nullptr));
        featherFalloffLabel->setText(QApplication::translate("hlsl1Class", "\347\276\275\345\214\226\350\241\260\345\207\217", nullptr));
        DilateErodeValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        featherFalloffComboBox->setItemText(0, QApplication::translate("hlsl1Class", "\345\271\263\346\273\221", nullptr));
        featherFalloffComboBox->setItemText(1, QApplication::translate("hlsl1Class", "\347\220\203\347\212\266", nullptr));
        featherFalloffComboBox->setItemText(2, QApplication::translate("hlsl1Class", "\346\240\271\345\207\270", nullptr));
        featherFalloffComboBox->setItemText(3, QApplication::translate("hlsl1Class", "\345\271\263\346\226\271\345\217\215\346\257\224", nullptr));
        featherFalloffComboBox->setItemText(4, QApplication::translate("hlsl1Class", "\351\224\220\345\210\251", nullptr));
        featherFalloffComboBox->setItemText(5, QApplication::translate("hlsl1Class", "\347\272\277\346\200\247", nullptr));

        MaskComboBox->setItemText(0, QApplication::translate("hlsl1Class", "\346\226\271\345\275\242", nullptr));
        MaskComboBox->setItemText(1, QApplication::translate("hlsl1Class", "\346\244\255\345\234\206", nullptr));

        XLabel_2->setText(QApplication::translate("hlsl1Class", "x:", nullptr));
        TransparentLabel_2->setText(QApplication::translate("hlsl1Class", "\351\200\217\346\230\216\345\272\246\357\274\232", nullptr));
        MaskTypeComboBox->setItemText(0, QApplication::translate("hlsl1Class", "\347\233\270\345\212\240", nullptr));
        MaskTypeComboBox->setItemText(1, QApplication::translate("hlsl1Class", "\347\233\270\345\207\217", nullptr));
        MaskTypeComboBox->setItemText(2, QApplication::translate("hlsl1Class", "\346\255\243\347\211\207\345\217\240\345\272\225\357\274\210\347\233\270\344\271\230\357\274\211", nullptr));
        MaskTypeComboBox->setItemText(3, QApplication::translate("hlsl1Class", "\351\235\236", nullptr));

        MaskComboBox_2->setItemText(0, QApplication::translate("hlsl1Class", "\346\226\271\345\275\242", nullptr));
        MaskComboBox_2->setItemText(1, QApplication::translate("hlsl1Class", "\346\244\255\345\234\206", nullptr));

        CoreMatteCheckBox->setText(QApplication::translate("hlsl1Class", "\346\240\270\345\277\203\351\201\256\347\275\251", nullptr));
        XLabel->setText(QApplication::translate("hlsl1Class", "x:", nullptr));
        RotationLabel_2->setText(QApplication::translate("hlsl1Class", "\346\227\213\350\275\254\357\274\232", nullptr));
        WidthLabel->setText(QApplication::translate("hlsl1Class", "\345\256\275\345\272\246:", nullptr));
        MaskTypeComboBox_2->setItemText(0, QApplication::translate("hlsl1Class", "\347\233\270\345\212\240", nullptr));
        MaskTypeComboBox_2->setItemText(1, QApplication::translate("hlsl1Class", "\347\233\270\345\207\217", nullptr));
        MaskTypeComboBox_2->setItemText(2, QApplication::translate("hlsl1Class", "\346\255\243\347\211\207\345\217\240\345\272\225\357\274\210\347\233\270\344\271\230\357\274\211", nullptr));
        MaskTypeComboBox_2->setItemText(3, QApplication::translate("hlsl1Class", "\351\235\236", nullptr));

        MaskLabel_2->setText(QApplication::translate("hlsl1Class", "\351\201\256\347\275\251\357\274\232", nullptr));
        WidthLabel_2->setText(QApplication::translate("hlsl1Class", "\345\256\275\345\272\246:", nullptr));
        MaskTypeLabel->setText(QApplication::translate("hlsl1Class", "\351\201\256\347\275\251\347\261\273\345\236\213\357\274\232", nullptr));
        TransparentLabel->setText(QApplication::translate("hlsl1Class", "\351\200\217\346\230\216\345\272\246\357\274\232", nullptr));
        HeightLabel_2->setText(QApplication::translate("hlsl1Class", "\351\253\230\345\272\246\357\274\232", nullptr));
        HeightLabel->setText(QApplication::translate("hlsl1Class", "\351\253\230\345\272\246\357\274\232", nullptr));
        MaskLabel->setText(QApplication::translate("hlsl1Class", "\351\201\256\347\275\251\357\274\232", nullptr));
        YLabel->setText(QApplication::translate("hlsl1Class", "y:", nullptr));
        MaskTypeLabel_2->setText(QApplication::translate("hlsl1Class", "\351\201\256\347\275\251\347\261\273\345\236\213\357\274\232", nullptr));
        YLabel_2->setText(QApplication::translate("hlsl1Class", "y:", nullptr));
        RotationLabel->setText(QApplication::translate("hlsl1Class", "\346\227\213\350\275\254\357\274\232", nullptr));
        GarbageMatteCheckBox->setText(QApplication::translate("hlsl1Class", "\345\236\203\345\234\276\351\201\256\347\275\251", nullptr));
        CompositeRadioButton->setText(QApplication::translate("hlsl1Class", "composite", nullptr));
        SelectBackgroundButton->setText(QApplication::translate("hlsl1Class", "\345\257\274\345\205\245\350\203\214\346\231\257\345\233\276\345\203\217", nullptr));
        SelectVideoButton->setText(QApplication::translate("hlsl1Class", "\345\257\274\345\205\245\350\247\206\351\242\221", nullptr));
        SelectKinectButton->setText(QApplication::translate("hlsl1Class", "Kinect", nullptr));
        getOneFrameButton->setText(QApplication::translate("hlsl1Class", "Kinect\350\216\267\345\217\226\344\270\200\345\270\247", nullptr));
        gammaLabel->setText(QApplication::translate("hlsl1Class", "gamma\346\240\241\346\255\243", nullptr));
        contrastLabel->setText(QApplication::translate("hlsl1Class", "\345\257\271\346\257\224\345\272\246", nullptr));
        sharpLabel->setText(QApplication::translate("hlsl1Class", "\351\224\220\345\214\226", nullptr));
        brightnessLabel->setText(QApplication::translate("hlsl1Class", "\344\272\256\345\272\246", nullptr));
        contrastValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        sharpValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        gammaValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        brightnessValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
        binarizationLabel->setText(QApplication::translate("hlsl1Class", "\344\272\214\345\200\274\345\214\226", nullptr));
        binaryCheckBox->setText(QApplication::translate("hlsl1Class", "\344\272\214\345\200\274\345\214\226", nullptr));
        binarizationValueLabel->setText(QApplication::translate("hlsl1Class", "0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class hlsl1Class: public Ui_hlsl1Class {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HLSL1_H
